### ISSUE TITLE
Alfresco Community deployment with ansible pg_hba.conf.j2 local_addr error

### ISSUE THREAD

**Issue by AlexMutuelleJust** [Alfresco/alfresco-ansible-deployment#382] opened 2022-07-12 15:33 UTC
Hello everyone,

I am discovering Ansible, I need your expertise for this error message:
```
TASK [../roles/postgres : Configure postgresql client auth] *********************************************************************************************************************************************************************************
task path: /opt/ansiblealfresco/alfresco-ansible-deployment-2.0.0/roles/postgres/tasks/main.yml:41
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: root
<localhost> EXEC /bin/sh -c 'echo ~root && sleep 0'
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp `"&& mkdir "` echo /root/.ansible/tmp/ansible-tmp-1657639107.27-13718-160893885570647 `" && echo ansible-tmp-1657639107.27-13718-160893885570647="` echo /root/.ansible/tmp/ansible-tmp-1657639107.27-13718-160893885570647 `" ) && sleep 0'
<localhost> EXEC /bin/sh -c 'rm -f -r /root/.ansible/tmp/ansible-tmp-1657639107.27-13718-160893885570647/ > /dev/null 2>&1 && sleep 0'
fatal: [localhost]: FAILED! => {
    "changed": false,
    "msg": "AnsibleUndefinedVariable: 'unicode object' has no attribute 'local_addr'"
}

PLAY RECAP **********************************************************************************************************************************************************************************************************************************
localhost                  : ok=17   changed=0    unreachable=0    failed=1    skipped=9    rescued=0    ignored=0
```

I am playing this command:

```
# ansible-playbook playbooks/acs.yml -i inventory_local.yml -e "@community-extra-vars.yml" -vvv
```

I found out the 'local_addr' is in the pg_hba.conf.j2 but i have no clue how to resolve it.

Need a little help please :D

Regards, Alexandre

**Comment by gionn** [comment] 2022-07-12 15:50
Hello,

local_addr should get automatically populated from [here](https://github.com/Alfresco/alfresco-ansible-deployment/blob/ffd8a9438c62a7367ca0eb414af42f7366559f76/roles/common/defaults/main.yml#L19), gathering `ansible_default_ipv4.address` fact from the repo host defined in the inventory (localhost in your case).

From where are you running the playbook? Operating system / platform

**Comment by alxgomz** [comment] 2022-07-12 16:04
The only thing that's needed on your target host, for ansible to be able to automatically populate the `ansible_default_ipv4.address` should be a default route. Do you have one?

**Comment by AlexMutuelleJust** [comment] 2022-07-12 17:12
> Hello,
> 
> local_addr should get automatically populated from [here](https://github.com/Alfresco/alfresco-ansible-deployment/blob/ffd8a9438c62a7367ca0eb414af42f7366559f76/roles/common/defaults/main.yml#L19), gathering `ansible_default_ipv4.address` fact from the repo host defined in the inventory (localhost in your case).
> 
> From where are you running the playbook? Operating system / platform

Hello Gionn, 
I am running it from CentOS7 fully updated.
It's a full local single host installation.

**Comment by AlexMutuelleJust** [comment] 2022-07-12 17:13
> The only thing that's needed on your target host, for ansible to be able to automatically populate the `ansible_default_ipv4.address` should be a default route. Do you have one?

Hello AlxGomz

I'm pretty sure I got one. Let me tomorrow to check this and keep you on touch.

**Comment by AlexMutuelleJust** [comment] 2022-07-13 05:57
> The only thing that's needed on your target host, for ansible to be able to automatically populate the `ansible_default_ipv4.address` should be a default route. Do you have one?

 Hi AlxGomz
 
 `# ip route
default via xx.xx.xx.5 dev eth0 proto static metric 100
xx.xx.xx.0/24 dev eth0 proto kernel scope link src xx.xx.xx.121 metric 100`

Default route is ok.

Regards, Alexandre

**Comment by alxgomz** [comment] 2022-07-13 09:26
can you check the version of Ansible you're using? This `unicode object`'s property error makes me think ansible is not dealing `repo_hosts` list of objects and I'm wondering wether that could because of an older ansible version.
Ideally you should provide info asked in the issue template to avoid back and forth comms.

Thank you.

**Comment by AlexMutuelleJust** [comment] 2022-07-13 09:29
Here it is:

`# ansible --version
ansible 2.9.27
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Jun 28 2022, 15:30:04) [GCC 4.8.5 20150623 (Red Hat 4.8.5-44)]`
  
  You think I should update it?
  
  Thank you

**Comment by alxgomz** [comment] 2022-07-13 09:40
Yes,
Although we never faced that specific issue, we know of others which happen when using ansible version before 2.12.
For that reason we enforced  2.12+ as a requirement (and also because 2.12 is the currently supported version, [2.9 support has ended](https://docs.ansible.com/ansible/latest/reference_appendices/release_and_maintenance.html#ansible-core-changelogs))
See [this doc](https://github.com/Alfresco/alfresco-ansible-deployment/blob/master/docs/deployment-guide.md#setup-a-control-node) for a way to easily match the dependencies
I'm almost sure that's the cause of the issue you're facing so I'll close this issue for now but feel free to reopen it or a new one in case the problem remains.

**Closed by alxgomz** 2022-07-13 09:40 UTC

**Comment by AlexMutuelleJust** [comment] 2022-07-13 09:45
I do that today and give a feedback!

Thanks!
