### ISSUE TITLE
Unable to create new user with new installation 7.3 Community with this github deployment 

### ISSUE THREAD

**Issue by lucturbide** [Alfresco/alfresco-ansible-deployment#547] opened 2023-02-16 16:51 UTC
#### Bug description

I make new install of Alfresco 7.3 with the last github alfresco-ansible-deployment on multiple platforms like CentOS 7, CenOS 8 and Ubuntu 22.04. On all installations, I always encounter the same problem: Failure, We couldn't create user.
There are also other functions that do not work. I don't seem to have permission to use Alfresco 7.3 Community. I don't see any errors during installation and no errors in the logs. Any clues?

#### Target OS

Ubuntu 22.04 

#### Ansible error

No error

Installation on VMware Ubuntu 22.04 Desktop.
git clone https://github.com/Alfresco/alfresco-ansible-deployment.git
cd alfresco-ansible-deployment/
pip install --user pipenv
sudo apt install pipenv -y
cd playbooks/
pipenv install --deploy
cd ..
pipenv run ansible-galaxy install -r requirements.yml
pipenv run ansible-playbook --ask-vault-pass playbooks/acs.yml
openssl rand -base64 21 >  ~/.vault_pass.txt

export ANSIBLE_VAULT_PASSWORD_FILE=~/.vault_pass.txt
pipenv run ansible-playbook -e vault_init=encrypted_variables playbooks/secrets-init.yml
pipenv run ansible-playbook playbooks/acs.yml -i inventory_local.yml -e "@community-extra-vars.yml"

(I access with my web brower to /share, login with admin,admin, go to Admin Tools and try to create New User  
Failure, We couldn't create user. When I submit form)

PLAY RECAP *********************************************************************************************************************************************
localhost                  : ok=207  changed=112  unreachable=0    failed=0    skipped=206  rescued=0    ignored=0

**Comment by gionn** [comment] 2023-02-16 16:56
Hello, may be a duplicate of https://github.com/Alfresco/alfresco-ansible-deployment/issues/505#issuecomment-1321594776 (CORS configuration issue that as a side effect break the user creation feature)

That should not happen if you access the application on localhost, though.

**Comment by lucturbide** [comment] 2023-02-16 19:01
Yes, localhost work! Ok I fix the problem by seting CORS.ENABLE = FALSE

Thank

**Comment by gionn** [comment] 2023-02-17 09:23
Thanks for confirming!

**Closed by gionn** 2023-02-17 09:23 UTC
Labels: question
