### ISSUE TITLE
Missing newline in setenv.sh can cause ActiveMQ to fail to start

### ISSUE THREAD

**Issue by amthmsExprn** [Alfresco/alfresco-ansible-deployment#199] opened 2021-08-30 11:43 UTC
The missing newline causes ActiveMQ to fail to start as the PATH set up gets corrupted when ansible customizes the setenv.sh template and it is deployed. The corrupted PATH causes basic linux commands to be missing and the service to fail on startup.

**Environment**:
Ansible Host: RHEL 7.9
Ansible Controller: Ansible 2.10.3

File: roles/java/templates/setenv.sh

**Newline removed:**
https://github.com/Alfresco/alfresco-ansible-deployment/commit/11fd0289eb71adef2d62c054196e301500f9e612

**Causes the customization to corrupt the setenv.sh PATH setup**
- name: Add activemq_home and host to setenv script
  become: true
  become_user: "{{ username }}"
  blockinfile:
    path: "{{ config_folder }}/setenv.sh"
    marker: "# {mark} ACTIVEMQ ENV VARS"
    block: |
      export ACTIVEMQ_HOME={{ activemq_home }}
      export ACTIVEMQ_HOST={{ activemq_host }}

**The deployed setenv.sh used by the ActiveMQ Service can end up like:**
#!/bin/sh

export JAVA_HOME="/opt/openjdk-11.0.7"
export PATH="${JAVA_HOME}/bin:${PATH}"**# BEGIN ACTIVEMQ ENV VARS**
...

**Comment by alxgomz** [comment] 2021-09-07 08:17
Hi @amthmsExprn ,

I just did a test using the config bellow (centos7):
```
ansible 2.10.13
  config file = None
  configured module search path = ['/home/alxgomz/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/alxgomz/.virtualenvs/ansible2103/lib/python3.9/site-packages/ansible
  executable location = /home/alxgomz/.virtualenvs/ansible2103/bin/ansible
  python version = 3.9.2 (default, Feb 28 2021, 17:03:44) [GCC 10.2.1 20210110]
```
and the setenv.sh is properly created:
```
 cat /etc/opt/alfresco/setenv.sh 
#!/bin/sh

export JAVA_HOME="/opt/openjdk-11.0.12"
export PATH="${JAVA_HOME}/bin:${PATH}"
# BEGIN ACTIVEMQ ENV VARS
export ACTIVEMQ_HOME=/opt/apache-activemq-5.16.1
export ACTIVEMQ_HOST=192.168.0.187
# END ACTIVEMQ ENV VARS
```
Are you sure you're not using a fork again?

**Comment by alxgomz** [comment] 2021-09-07 11:22
I just realize that I used the wrong ansible version to test (2.10.13 instead of your 2.10.3).
I can indeed reproduce using 2.10.3.
However this is not a but on our side but instead this is a bug on ansible side which has been fixed in 2.10.4. Please upgrade.

Referenced upstream issue:
[https://github.com/ansible/ansible/issues/72055](https://github.com/ansible/ansible/issues/72055 )

**Comment by alxgomz** [comment] 2021-09-07 11:22
closing as not a bug

**Closed by alxgomz** 2021-09-07 11:22 UTC

**Comment by amthmsExprn** [comment] 2021-09-13 15:30
In an ok, better, best situation I would advocate for adding the newline. But I understand closing it/not prioritizing it.
